### ISSUE TITLE
最低支持版本是不是有点高了？

### ISSUE THREAD

**Issue by hudan2714** [GitLqr/LQROptionItemView#1]
minSdkVersion最低16？应该可以是16以下吧

**Comment by GitLqr** [comment]
如今应用类的app还有低过16的？现在的手机的系统基本都是5.0以上了，要说低点的普通是4.4，这个项目最低要求4.1不过分吧。

**Comment by hudan2714** [comment]
我们支持的是4.0.。。。15的。

**Comment by GitLqr** [comment]
你可以把这个工程中library module的OptionItemView.java文件和attrs_oiv.xml里的内容复制到你的项目中，就两个文件而已，这样就可以用了。

**Comment by hudan2714** [comment]
谢谢了。。。其实你这个是可以支持更低版本的。。

**Comment by GitLqr** [comment]
好，如果下次有更新的话我会把版本高低的
